theme: jekyll-theme-time-machine
title: Rafael Moreno
description: É possível criar uma página em GitHub Pages de forma simples e sem custos!
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin
languages: ["en", "pt-pt", "pt-br"]
exclude: https://code.jquery.com/jquery-1.12.4.min.js
